using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FaxCore.Ev6.RestClient.Models.Response
{
    /// <summary>
    ///     This is the response generated by a file upload.
    /// </summary>
    public class UploadResponse
    {
        /// <summary>
        ///     The unique id of the uploaded file
        /// </summary>
        [DataMember(Name = "id")]
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        ///     The filename of the uploaded file on the server.
        /// </summary>
        [DataMember(Name = "fileName")]
        [JsonPropertyName("fileName")]
        public string FileName { get; set; }
    }
}